name: genphoto1
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.1.1
  - torchvision=0.16.1
  - torchaudio=2.1.1
  - pytorch-cuda=12.1
  - pip
  - pip:
    - diffusers==0.25.0
    - xformers==0.0.23
    - imageio==2.36.0
    - imageio[ffmpeg]
    - opencv-python
    - transformers==4.45.0
    - accelerate==0.26.0
    - huggingface-hub==0.25.2
    - numpy==1.26.4
    - gdown
    - einops
    - decord
    - omegaconf
    - safetensors
    - gradio
    - wandb
    - triton
    - termcolor
    - lpips
    - git+https://github.com/openai/CLIP.git
